# Generated by Django 4.2 on 2024-09-09 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=12, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='이메일 주소')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성')], max_length=1, null=True, verbose_name='성별')),
                ('birth', models.DateField(null=True, verbose_name='생년월일')),
                ('cash', models.IntegerField(default=10000, verbose_name='캐쉬')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
