# Generated by Django 4.2 on 2024-09-09 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('photocards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.PositiveSmallIntegerField(choices=[(1, '판매 중'), (2, '판매 완료')], default=1, verbose_name='판매 상태')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='판매 가격')),
                ('fee', models.PositiveIntegerField(default=0, verbose_name='수수료')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='생성 일시')),
                ('renewal_date', models.DateTimeField(auto_now=True, verbose_name='수정 일시')),
                ('sold_date', models.DateTimeField(null=True, verbose_name='판매 일시')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_set', related_query_name='order', to='users.user', verbose_name='구매자')),
                ('photocard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_set', related_query_name='sale', to='photocards.photocard', verbose_name='포토카드')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_set', related_query_name='sale', to='users.user', verbose_name='판매자')),
            ],
        ),
    ]
